### ISSUE TITLE
[DISCUSS] more yaml friendly spec

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/bumblebee#1]
How about something like:

```
kind: Transformation
metadata:
  name: demo
spec:
  transform:
  - delete:
     - extra
  - shift:
     - not-foo: foo
     - bar.baz: foo.baz
  - concat:
     sources:
     - value: "hello"
       path : "project"
    targetPath: sub.project
    delim: ","
  - uuid: sub.uuid
  eventType: ce.after.transformation
  eventSource: foo
  id: 
  ceOverides:
  - 
```

Basically we can re-craft the full cloudevent and its payload
