### ISSUE TITLE
Do not convert phone numbers to float64

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/bumblebee#23]
"Add" operation with the following data
```
...
  - name: add
    paths:
    - key: to
      value: "+19196000253"
```

will produce an output with 
```
    "to": 19196000253
```
which is obviously wrong behaviour. The issue is that phone number format turned out to has a float64 compatible value:
```
		f, err := strconv.ParseFloat("+19196000253", 64)
		if err == nil {
			return f
		}
```
-this will not produce an error :(
